### ISSUE TITLE
Failure to adhere to MIT License

### ISSUE THREAD

**Issue by shirts** [pedrofurtado/microsoft_teams_incoming_webhook_ruby#1]
Hey there 👋

This code was copied from [my repo](https://github.com/shirts/microsoft-teams-ruby), that you are a contributor of, without preserving the copyright.

https://github.com/shirts/microsoft-teams-ruby

Would appreciate a resolution on your end, new versions pushed to RubyGems etc. 

https://opensource.stackexchange.com/questions/8853/can-i-change-the-copyright-holder-name-and-year-of-an-mit-license
https://opensource.stackexchange.com/questions/11806/what-to-do-if-someone-forked-your-project-and-removed-its-license

Thanks.

**Comment by pedrofurtado** [comment]
Hello, @shirts ! How are you?

Yeap, the repo is like a fork from original gem, with some other improvements based on use cases here.

Sorry for any inconvenience made here about licenses and copyright, I am not a expert on this 😆 

I've created a PR with this purpose, can you help me to check if this changes are the needed changes for license correctness?

https://github.com/pedrofurtado/microsoft_teams_incoming_webhook_ruby/pull/2

Thanks!
